-- MySQL Script generated by MySQL Workbench
-- Wed Mar 12 16:46:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pet-supermarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pet-supermarket` ;

-- -----------------------------------------------------
-- Schema pet-supermarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pet-supermarket` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pet-supermarket` ;

-- -----------------------------------------------------
-- Table `pet-supermarket`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`users` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`users` (
  `user_id` BIGINT NOT NULL,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `full_name` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`roles` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`roles` (
  `role_id` BIGINT NOT NULL,
  `role_name` VARCHAR(50) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`manufacturers` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`manufacturers` (
  `manufacturer_id` BIGINT NOT NULL,
  `manufacture_name` VARCHAR(255) NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`discounts` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`discounts` (
  `discount_id` BIGINT NOT NULL,
  `discount_percentage` BIGINT(3) NULL,
  `discount_amount` DECIMAL NULL,
  `dicount_desc` VARCHAR(45) NULL,
  `discount_expiry` DATETIME(6) NULL,
  `discount_updated` DATETIME(6) NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`product_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`product_details` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`product_details` (
  `product_id` BIGINT NOT NULL,
  `product_name` VARCHAR(255) NULL,
  `product_desc` VARCHAR(255) NULL,
  `unit_price` DECIMAL NULL,
  `manufacturer_id` BIGINT NULL,
  `current_discount` BIGINT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_manufacturers1_idx` (`manufacturer_id` ASC) VISIBLE,
  INDEX `fk_product_details_discounts1_idx` (`current_discount` ASC) VISIBLE,
  CONSTRAINT `fk_products_manufacturers1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `pet-supermarket`.`manufacturers` (`manufacturer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_details_discounts1`
    FOREIGN KEY (`current_discount`)
    REFERENCES `pet-supermarket`.`discounts` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`images` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`images` (
  `img_id` BIGINT NOT NULL,
  `img_url` VARCHAR(255) NULL,
  `product_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `discount_id` BIGINT NOT NULL,
  PRIMARY KEY (`img_id`),
  INDEX `fk_images_product_details1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_images_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_images_discounts1_idx` (`discount_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_product_details1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pet-supermarket`.`product_details` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pet-supermarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_discounts1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `pet-supermarket`.`discounts` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`user_role` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`user_role` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  INDEX `fk_user_role_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_role_roles1_idx` (`role_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_role_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pet-supermarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `pet-supermarket`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`products` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`products` (
  `product_id` BIGINT NOT NULL,
  `type_name` VARCHAR(255) unique,
  INDEX `fk_prod_types_products1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`product_id`, `type_name`),
  CONSTRAINT `fk_prod_types_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pet-supermarket`.`product_details` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`orders` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`orders` (
  `order_id` BIGINT NOT NULL,
  `total_price` DECIMAL NULL,
  `user_id` BIGINT NULL,
  `quantity` VARCHAR(45) NULL,
  `purchased` BIT NOT NULL,
  `order_updated` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pet-supermarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`order_prod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`order_prod` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`order_prod` (
  `product_id` BIGINT NOT NULL,
  `type_name` VARCHAR(45) NOT NULL,
  `order_id` BIGINT NOT NULL,
  `subQuantity` BIGINT NULL,
  `subPrice` DECIMAL NULL,
  `applied_discount` BIGINT NULL,
  INDEX `fk_order_prod_products1_idx` (`product_id` ASC, `type_name` ASC) VISIBLE,
  INDEX `fk_order_prod_orders1_idx` (`order_id` ASC) VISIBLE,
  PRIMARY KEY (`product_id`, `type_name`, `order_id`),
  INDEX `fk_order_prod_discounts1_idx` (`applied_discount` ASC) VISIBLE,
  CONSTRAINT `fk_order_prod_products1`
    FOREIGN KEY (`product_id` , `type_name`)
    REFERENCES `pet-supermarket`.`products` (`product_id` , `type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_prod_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `pet-supermarket`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_prod_discounts1`
    FOREIGN KEY (`applied_discount`)
    REFERENCES `pet-supermarket`.`discounts` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`pets` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`pets` (
  `pet_id` BIGINT NOT NULL,
  `pet_name` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`prod_pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`prod_pet` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`prod_pet` (
  `product_id` BIGINT NOT NULL,
  `pet_id` BIGINT NOT NULL,
  INDEX `fk_prod_pet_products1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`product_id`),
  INDEX `fk_prod_pet_pets1_idx` (`pet_id` ASC) VISIBLE,
  CONSTRAINT `fk_prod_pet_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pet-supermarket`.`product_details` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prod_pet_pets1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `pet-supermarket`.`pets` (`pet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pet-supermarket`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pet-supermarket`.`favorites` ;

CREATE TABLE IF NOT EXISTS `pet-supermarket`.`favorites` (
  `user_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  INDEX `fk_favorites_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_favorites_product_details1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `product_id`),
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pet-supermarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_product_details1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pet-supermarket`.`product_details` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
